# Site settings
title: HJ blog
description: Study Notes
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Statistical Study Notes
user_description: I'm a statistics graduate student. Visit my blog here ":" <a href="https://blog.naver.com/jinis_stat" target="_blank"> https://blog.naver.com/jinis_stat</a>
user_title: Projects and Research by Hyejin Sim
email: simhj79@yonsei.ac.kr
#twitter_username: lorem_ipsum
github_username:  "HyeJin, Sim"
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
